apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ include "n8n.fullname" . }}, role: api }
  template:
    metadata:
      labels: { app: {{ include "n8n.fullname" . }}, role: api }
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: n8n
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef: { name: {{ include "n8n.fullname" . }}-config }
            - secretRef:    { name: {{ include "n8n.fullname" . }}-secret }
          ports:
            - name: http
              containerPort: 5678
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /home/node/.n8n
            {{- end }}
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}-data
        {{- end }}