apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
type: Opaque
stringData:
  DB_POSTGRESDB_PASSWORD: "{{ .Values.secret.database.postgresdb.password }}"
  N8N_BASIC_AUTH_ACTIVE: "{{ .Values.secret.security.basicAuth.active }}"
  N8N_BASIC_AUTH_USER: "{{ .Values.secret.security.basicAuth.user }}"
  N8N_BASIC_AUTH_PASSWORD: "{{ .Values.secret.security.basicAuth.password }}"
  QUEUE_BULL_REDIS_PASSWORD: "{{ .Values.secret.redis.password }}"