apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-config
data:
  redis.conf: |
    {{- if .Values.auth.enabled }}requirepass {{ .Values.auth.password }}{{ end }}
    appendonly yes
