apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  type: {{ .Values.service.type }}
  selector: { app: {{ .Release.Name }}-redis }
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: 6379
