apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  type: {{ .Values.service.type }}
  selector: { app: {{ .Release.Name }}-postgresql }
  ports:
    - name: pg
      port: {{ .Values.service.port }}
      targetPort: 5432
